export const PRIVATE_KEY = "24GShzixEKJfstePdF3bKkHPEyPNvjeci2yZNGYmCFaMtUHNnBz4HvCarBtEAcqn2VtMh6EwwK78Zp3DFFf9qXrD";
export const PUBLIC_KEY = "HpYep3WV1aeHwUgPhrTtDwG2uXbELyLmCRMWjhe2GBfK";

export const TOKEN_MINT_ADDRESS = "7ERx9XkcxDHhJbyNq2wDhHcxGRkDyjFp8fT5FKKUfCWj";